
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int FPAR = 22;
  public static final int MENOS = 16;
  public static final int TRIPLO = 19;
  public static final int MENOR = 10;
  public static final int ENTAO = 13;
  public static final int ELSE = 8;
  public static final int VEZES_MULT = 24;
  public static final int IGUAL = 11;
  public static final int SEMI = 2;
  public static final int DIVIDIDO = 17;
  public static final int INTERROGACAO = 23;
  public static final int ESCREVA = 6;
  public static final int GUARDE = 3;
  public static final int APAR = 21;
  public static final int IF = 7;
  public static final int ID = 5;
  public static final int DOBRO = 18;
  public static final int STRING = 12;
  public static final int MAIS = 15;
  public static final int EOF = 0;
  public static final int NUMERO = 25;
  public static final int error = 1;
  public static final int MAIOR = 9;
  public static final int BOOL = 26;
  public static final int EM = 4;
  public static final int VEZES = 14;
  public static final int METADE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "GUARDE",
  "EM",
  "ID",
  "ESCREVA",
  "IF",
  "ELSE",
  "MAIOR",
  "MENOR",
  "IGUAL",
  "STRING",
  "ENTAO",
  "VEZES",
  "MAIS",
  "MENOS",
  "DIVIDIDO",
  "DOBRO",
  "TRIPLO",
  "METADE",
  "APAR",
  "FPAR",
  "INTERROGACAO",
  "VEZES_MULT",
  "NUMERO",
  "BOOL"
  };
}

